version: '3.1'

services:
  db:
    image: mysql:8.0.29
    restart: always
    container_name: mysql8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - C:\Users\vitor\Documents\Alura\ws-ms-alura-food\volumes\data:/var/lib/mysql
      - C:\Users\vitor\Documents\Alura\ws-ms-alura-food\volumes\conf.d:/etc/mysql/conf.d

  